name: Generate JSON

on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest
    env:
      filename: escalade-orsay
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set current date
        run: |
          echo "dateNow=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Generate JSON
        run: python src/main.py ${{ env.dateNow }}_${{ env.filename }}.json

      - name: Upload JSON
        uses: actions/upload-artifact@v3
        with:
          name: json_${{ github.run_number }}_${{ github.run_id }}
          path: ${{ env.dateNow }}_${{ env.filename }}.json
